# These are supported funding model platforms

github: [weppos]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: weppos # Replace with a single Ko-fi username
tidelift: "rubygems/whois"
custom: https://whoisrb.org/contribute/#donate
